== Why This Guide Exists
I'll be frank: this guide exists because of my frustrations with the User Interface (UI) currently implemented in FarSight Studios' _The Pinball Arcade_ (TPA) for Android. My personal opinion is the UI is limiting, it confuses customers, and offers a poor User Experience (UX) for new users (and even seasoned users familiar with TPA in some cases).

There has been talk of FarSight updating the UI. But they have been saying that for at least a year now, and nothing gets done. The user base swells, but the UX still remains untouched. I've been working around issues caused by the UI for at least that long, and the number of cases I've encountered where customers are just plain confused about features is getting to the point where I have no choice but to take action.

I'm trying to solve some of these issues by writing this user guide. The guide contains information about features in TPA that can't be adequately explained in-game because of a combination of UI limitations and the complexity of the feature.

This guide is not a tool created to disrespect FarSight and their product. Quite the opposite: it is a factual testimonial from a customer (who happens to be a volunteer beta tester and Technical Writer) who feels it's necessary to create a user guide for a game that really shouldn't need one. A lot of things in this guide can be figured out by playing around with the UI. But there are some things that really aren't intuitive, and some things that if you assume you know how they work, you may be unpleasantly surprised down the track.

I hope that if you are a new user to TPA Android, this guide helps you get the most out of the app. I hope that if someone at FarSight reads this, they understand the intent and take urgent action to address the workarounds and caveats I've documented in here.
