= The Pinball Arcade Android Users Guide

== What Is This?
The Pinball Arcade Android User Guide has been created--somewhat out of frustration--to help Android users of FarSight Studio's The Pinball Arcade (TPA) app.

== Why Should I Read This?
If you are a new user to the game, there are plenty of options you need to configure so your device works the way it should with TPA, but might not know how because the UI is simply not able to explain them in sufficient detail.

== I Want To Help
I'd love your help! Please open an issue and tell me what needs improving.

== I Want To Contribute Directly
If you think something could be improved, please fork the repo and submit a pull request.

== I Want To Support You
If this guide has helped you configure your Android device correctly, consider donating through PayPal to jaredleonmorgan {at} gmail {dot} com. I am not employed by FarSight in any way, and volunteer my time to them Beta Testing their software because I am passionate about quality and a solid User Experience (UX).
