[[Settings_Menu]]
== The Settings Menu Explained
Because of User Interface limitations (long and protracted story), the Settings menu is a bit of a mess. There are some options that use Developer speak and would be meaningless to many users, yet are very important for configuring optimum performance in Android.

=== Important Settings Menu Items
The menu items that make a difference to graphics or performance are:

* Manage Tables
* Sound
* Mip Mapping
* Detail
* Textures

=== Other Settings Menu Items

The rest of these options really belong in another menu. I've suggested this in http://pinballarcadefans.com/showthread.php/9603-Improve-the-Settings-Menu[this thread] but at the time of writing the issue has not been publicly acknowledged.

Controls::
Text instructions on how to use touchscreen controls. No info about controller support. No info about moving the Launch Button (see Touchscreen Controls)
Videos::
You can buy videos about the tables. I don't know why you would: this type of info is free on YouTube.
Our Mission::
What the game is all about.
FarSight Credits::
Who makes the game, and Kickstarter backer credits.
Twilight Zone Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Star Trek Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Terminator 2 Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Addams Family Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.

=== Important Options Explained

==== Manage Tables

TODO

==== Sound

TODO

==== Mip Mapping

TODO

==== Detail

TODO

==== Textures
