[[Settings_Menu]]
== The Settings Menu Explained
Because of User Interface limitations (long and protracted story), the Settings menu is a bit of a mess. There are some options that use Developer speak and would be meaningless to many users, yet are very important for configuring optimum performance in Android.

=== Important Settings Menu Items
The menu items that make a difference to graphics or performance are:

* Manage Tables
* Sound
* Mip Mapping
* Detail
* Textures

=== Other Settings Menu Items

The rest of these options really belong in another menu. I've suggested this in http://pinballarcadefans.com/showthread.php/9603-Improve-the-Settings-Menu[this thread] but at the time of writing the issue has not been publicly acknowledged.

Controls::
Text instructions on how to use touchscreen controls. No info about controller support. No info about moving the Launch Button (see Touchscreen Controls)
Videos::
You can buy videos about the tables. I don't know why you would: this type of info is free on YouTube.
Our Mission::
What the game is all about.
FarSight Credits::
Who makes the game, and Kickstarter backer credits.
Twilight Zone Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Star Trek Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Terminator 2 Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Addams Family Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.

=== Important Options Explained

==== Manage Tables

This menu is pretty self-explanatory. It lets you do the following:

Update All::
Update all owned tables for each GA release that have received RES updates (a term used to indicate a table has received improvements to graphics assets, known as 'resources'). 
Restore All:: 
Bulk download all tables linked to your Google Play account used to purchase TPA Table Packs, or Season Passes.
Delete::
There isn't a button clearly indicating this, but you can delete individual table files by tapping the button to the left of each table name.

NOTE: The table order in this list is well and truly out of alpha order. It is apparently sorted based on the date the table pack was released. That's why you see all the older tables from Season 1 and Season 2 appearing first. 

===== Managing Tables Outside the Interface

There is another way to manage tables that allows you to do away with the somewhat awkward menu in TPA. All you need is your favourite Android file browser.

The game Downloadable Content (DLC) is stored in the `/sdcard/Android/data/com.farsight.AndroidPinball.javaProject/files/` folder. 

It is arguably easier to navigate to this directory and delete files manually. The method through the UI is fine, but slow. Only use it if you are not comfortable deleting files through the file system.

Unless you have a very fast data connection, I'd strongly recommend you back up your DLC to DropBox, Copy, or even just to a folder on your computer. Just get them off your device. Depending on what Content Delivery Network (CDN) node you connect to, it might take anywhere between 30 minutes to four hours to restore all DLC to your device. Having a local copy synchronised to your device will make restoring faster. Much faster.

==== Sound

There's not a great deal to this menu: On or Off. But it is put into a position in the menu tree that is unintuitive.

Note that this turns off *all* sound effects and music. There are no subtle settings to affect mechanical sounds, music, or sound effects. 

==== Mip Mapping

TODO

==== Detail

TODO

==== Textures
