[[Controller_Settings]]
== Controller Configuration

This content was originally rolled up into a thread in http://pinballarcadefans.com/showthread.php/6662-Explained-Controller-Support-Options-for-Android[this thread] on the Pinball Arcade Fans forum. The thread rolls-up conversation fragments in http://pinballarcadefans.com/showthread.php/566-Controller-support-for-Android[this thread], to make it easier for folks to work out what controllers work with The Pinball Arcade (TPA) on Android.

=== Supported Controllers

The current set of controllers known to work with TPA Android are:

* http://store.mogaanywhere.com/Products/CPFA000253-01[Moga Pocket]
* http://www.mogaanywhere.com/controllers/moga-pro-controller/[Moga Pro] (in Mode B)
* http://www.amazon.com/PlayStation-Dualshock-Wireless-Controller-Black-3/dp/B0015AARJI/ref=sr_1_1?ie=UTF8&qid=1424752197&sr=8-1&keywords=playstation+3+controller[Playstation 3 SixAxis] (with SixAxis app in "Native Controller" mode. Must be rooted to use this app)
* Samurai Bluetooth Controller (GameStop brand)
* NVIDIA Shield Portable (in Mode A)
* NVIDIA Shield Tablet WiFi-Direct Controller (with NVidia Shield Tablet)


=== Abbreviations Used in this Section

LS::
Left Analog Stick
RS::
Right Analog Stick
L1/R1::
The top digital shoulder buttons on controllers.
L2/R2::
The bottom analog triggers (often analog) on controllers.
Mode A/B::
The Moga HID mode. Mode A (used by Moga Pocket and 3rd Party controllers) and Mode B (used by Moga Pro)
Type A/B::
TPA controller scheme setting, available within the in-game table menu. Switch between modes to switch the assigned flipper and magnasave shoulder/trigger buttons)

=== Moga Pocket

Left Flipper::
Left Shoulder Button
Right Flipper::
Right Shoulder Button
MagnaSave/Autoplunge button::
LS Up+Right
Launch Ball::
RS Down
Analog Tilt::
LS
View Lock::
X
Enter Initials::
Flipper Buttons, and Launch

NOTE: On Black Knight both Magnasave magnets are activated when lit when the controller command is entered. You will also tilt the table in that direction as well so be wary of tilting if you have been too aggressive up until that point.

=== Moga Pro / Playstation 3 / Shield Portable / Shield Tablet

Left Flipper::
L2, or L1 in Type A scheme
Right Flipper::
R2, or R1 in Type A scheme.
Special Button Left::
L1, or L2 in Type A scheme.
Special Button Right::
R1, or R2 in Type A scheme.
Launch::
RS Down
Analog Tilt::
LS
Lock Camera View::
X
Change Camera View::
Y
Select Menu Item/Launch Ball/Trigger Launch::
A
Back::
B
Enter Initials::
Flipper Buttons, and Launch (or A).
