[[Settings_Menu]]
== The Settings Menu Explained

User Interface limitations caused the Settings menu to evolve from a pretty terse list of items, to what is is now. 

There are some options that use Developer speak and would be meaningless to many users, yet are very important for configuring optimum performance in Android for older devices. 

Some Graphics menu items do not display depending on your device kernel flags and OpenGL capabilities (say what, now). 

The menu items that make a difference to playing and enjoying TPA are:

* Manage Tables
* Sound
* Mip Mapping
* Detail
* Textures

=== Manage Tables

This menu is pretty self-explanatory. It lets you do the following:

IMPORTANT: `Update All` and `Download Owned` do not run as background processes. You must have TPA open all the time for this process to complete successfully. 

Update All::
Update all _downloaded_ tables present on the device that have received RES updates (a term used to indicate a table has received improvements to graphics assets, known as 'resources'). 
Download Owned:: 
Bulk download all owned tables _missing from the app_, that are linked to your Google Play account used to purchase TPA Table Packs or Season Passes. 
Delete::
By tapping the button to the left of each table in the list, you can delete individual table files.

NOTE: The table order in this list is well and truly out of alphabetical order. It is sorted based on the date the table packs were released. That's why you see all the older tables from Season 1 and Season 2 appearing first. 

If you are starting from a new device, and you wanted to download and update all owned tables, you would select `Download Owned`. This will download all tables you own _in the order they were released_, starting at Season 1. 

If you already had all the tables on your device, and received an app update through Google Play, you would select `Update All` to pull down any updates table files. 

==== Managing Tables Outside the Interface

There is another way to manage tables that allows you to do away with the somewhat awkward menu in TPA. All you need is your favourite Android file browser.

The game Downloadable Content (DLC) is stored in the `/sdcard/Android/data/com.farsight.AndroidPinball.javaProject/files/` folder. 

It is arguably easier to navigate to this directory and delete files manually. The method through the UI works, but is slow. Only use it if you are not comfortable deleting files through the file system.

==== Back Up Your DLC

Unless you have a very fast data connection and you live in the United States, I'd *strongly recommend* you back up your DLC to DropBox, Copy, or even just to a folder on your computer. Just get them off your device. Depending on what Content Delivery Network (CDN) node you connect to, it might take anywhere between 30 minutes to four hours to restore all DLC to your device. Having a local copy synchronised to your device will make restoring faster. Much faster.

And use the new table release each month as a reminder to take a DLC back-up. You'll thank yourself later when you need to restore them all.

=== Sound

There's not a great deal to this menu: On or Off. 

Note that this turns off *all* sound effects and music. There are no subtle settings to affect mechanical sounds, music, or sound effects. This is most likely to do with limitations of the Farsight Audio Mixer, described later in this guide.

=== Mip Mapping

This menu screams "Developer Speak" in an app specifically not targeted at Developers. Another issue is the menu item has been misnamed: it should be _Anisotropic Filtering_. But try fitting that word into the current UI and you'll soon understand why Mip Mapping was chosen. 

You'll need to visit http://en.m.wikipedia.org/wiki/Mipmap[Wikipedia] for a concise description, but what this setting does is affect performance on devices in the area of "depth of field" and the sharpness of the depth of field.

You would think that turning this setting on would be a good thing. But, you need to turn your thinking around when understanding how this works in TPA.

On::
Activates the Mip Mapping function, which serves multiple mipmap images and lets the GPU pick the best sample resolution for your specific device hardware. This is better for devices with limited GPU capabilities.  
Off::
Deactivates the Mip Mapping function, which serves the highest resolution mipmap. This requires more GPU processing power, and as you can expect, this may add a performance impact for older devices.

The best advice for these two options is experiment with them on your device and see which setting delivers the best performance.

My suggestion for renaming this to something more user-friendly would be:

* Sharpness = High
* Sharpness = Normal

=== Detail

Detail -- or High LOD as most regular TPA Andorid forum users refer to it as -- was implemented http://pinballarcadefans.com/showthread.php/7358-High-lod-model-beta[mid February 2014].

Depending on the device you own, you might not even see this menu. Some Samsung devices featuring the Exynos System on a Chip (SoC) (MALI) architecture did not have a kernel flag set which caused this menu to be hidden. If you don't see this menu, your device has a GPU that will probably struggle to run TPA in general.

High LOD affects what individual elements you see on the table. If you turn this setting to Standard from High, you will really notice the difference. Elements like screw heads, transparencies, plastics, bulbs, even some playfield elements like the curly wires on Bally's _The Party Zone_ disappear. All these elements put strain on the GPU to render them, so if your device has a weak GPU this setting will either need to be set to Standard, or may not even be visible to you.

High::
All elements originally present on the table. This is the default for this menu now.
Normal::
Less table detail means that certain high-pologon objects are disabled. A performance boost is gained for older devices.

=== Textures

Textures is actually to do with Polygon counts in the models on the Tables. If you set this to the Normal setting, close ups of stand-up targets in Williams' _The Machine: Bride of Pinbot_ appear hexagonal. Set it to High, and they are far less hexagonal featuring about twice the polygon count.

High::
The highest polygon count possible in the table models used in TPA. This is the default for this menu now.
Normal::
Hexagonal shaped round targets, and other trade-offs that make some playfield elements appear jaggy at distance, and blocky when zoomed in upon.

== Other Settings Menu Items

The rest of these options really belong in another menu. I've suggested this in http://pinballarcadefans.com/showthread.php/9603-Improve-the-Settings-Menu[this thread] but at the time of writing the issue has not been publicly acknowledged.

Controls::
Text instructions on how to use touchscreen controls. There isn't room in this screen to go into detail about configuring touch regions, or using a Hardware Controller.
Videos::
You can purchase two videos to stream.
Our Mission::
What the game's primary mission is.
FarSight Credits::
The dedicated production team behind our favourite game.
Twilight Zone Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Star Trek Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Terminator 2 Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
Addams Family Credits::
Included only to meet the requirements of the Kickstarter award tiers for this table.
